# Generated by Django 3.0.7 on 2020-06-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200630_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='avatar_url',
            field=models.FileField(default='/avatar/default_avatar.jpg', upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.TextField(null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='info',
            name='cancel_time_avg',
            field=models.CharField(default='0', max_length=32, verbose_name='平均取消订单时长'),
        ),
        migrations.AlterField(
            model_name='info',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='是否验证邮箱'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='infoproviders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_providers', to=settings.AUTH_USER_MODEL),
        ),
    ]
