# Generated by Django 3.0.7 on 2020-06-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(help_text='1：充值，10：提现', verbose_name='交易类型')),
                ('txid', models.CharField(max_length=128, verbose_name='交易编号')),
                ('blockchain', models.CharField(max_length=32, verbose_name='区块网络')),
                ('coin_name', models.CharField(max_length=32, verbose_name='币种名称')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('fee', models.FloatField(verbose_name='手续费')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('address_tag', models.CharField(max_length=64, verbose_name='地址标签')),
                ('status', models.CharField(choices=[('VERIFY', 'verifying'), ('FAILED', 'failed'), ('SUBMIT', 'submitted'), ('REEXAMINE', 'reexamine'), ('CANCEL', 'canceled'), ('PASS', 'pass'), ('REJECT', 'reject'), ('PRE_TRANSFER', 'pre_transfer'), ('WALLET_TRANSFER', 'wallet_transfer'), ('WALLET_REJECT', 'wallet_reject'), ('CONFIRM_ERROR', 'confirm_error'), ('REPEAL', 'repealed'), ('CONFIRM', 'confirmed'), ('UNKNOWN', 'unknown'), ('CONFIRMING', 'confirming'), ('SAFE', 'safe'), ('ORPHAN', 'orphan')], max_length=32, verbose_name='状态')),
                ('error_code', models.CharField(max_length=32, verbose_name='错误代码')),
                ('error_message', models.CharField(max_length=256, verbose_name='错误内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=32, verbose_name='币种名称')),
                ('type', models.IntegerField(help_text='1：充值，10：提现', verbose_name='交易类型')),
                ('transact_type', models.CharField(choices=[('TRANSFER', 'transfer'), ('DEPOSIT', 'deposit'), ('WITHDRAW', 'withdraw'), ('WITHDRAW_FEE', 'withdraw_fee'), ('REBATE', 'rebate'), ('DEDUCTION', 'deduction'), ('OTHER', 'other')], max_length=32, verbose_name='订单类型')),
                ('amount', models.CharField(max_length=64, verbose_name='交易金额')),
                ('fee', models.CharField(max_length=64, verbose_name='手续费')),
                ('available_balance', models.CharField(max_length=64, verbose_name='可用余额')),
                ('account_balance', models.CharField(max_length=64, verbose_name='账户总余额')),
                ('prev_history_id', models.IntegerField(verbose_name='上一笔账单编号')),
                ('transact_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
